swagger: "2.0"
info:
  description: This is the swagger file that defines generated api
  version: "dev/0.0.1"
  title: titleeeee
consumes:
  - application/json
produces:
  - application/json

definitions:
  People:
    properties:
      id:
        type: string
        required: true
        description: Id of the element
      createdAt:
        type: string
      updatedAt:
        type: string

      age:
        type: integer
        required: false

      dead:
        type: boolean
        required: false

      name:
        type: string
        required: false



#base path for server application
basePath: /api
# Paths supported by the server application
paths:
  /people:
    get:
      operationId: listAll
      tags:
        - People
      summary: Read the entire list of people
      description: Read the list of people
      responses:
        200:
          description: Successfully read people list operation
          schema:
            $ref: '#/definitions/People'
    post:
      operationId: createOne
      tags:
        - People
      summary: Create a People and add it to the people list
      description: Create a new People in the people list
      parameters:
        - name: object
          in: body
          description: People to create
          required: True
          schema:
            $ref: '#/definitions/People'
      responses:
        201:
          description: Successfully created People in list

  /people/{id}:
    get:
      operationId: getOne
      tags:
        - People
      summary: Read one People from the people list
      description: Read one People from the people list
      parameters:
        - name: id
          in: path
          description: Unique model identifier for People
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            $ref: '#/definitions/People'
    put:
      operationId: updateOne
      tags:
        - People
      summary: Update a People in people
      description: Update a People in people
      parameters:
        - name: id
          in: path
          description: Unique model identifier for People
          type: string
          required: True
        - name: object
          in: body
          schema:
            $ref: '#/definitions/People'
      responses:
        200:
          description: Successfully updated People
    delete:
      operationId: deleteOne
      tags:
        - People
      summary: Delete a People from the people list
      description: Delete a person
      parameters:
        - name: id
          in: path
          type: string
          required: True
          description: Unique model identifier for People
      responses:
        200:
          description: Successfully deleted a People